// <auto-generated />
using System;
using Api_Mediconnet.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_Mediconnet.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250815185124_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TDiaSemana", b =>
                {
                    b.Property<int>("NDiaSemanaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(12)")
                        .HasColumnName("NDiaSemanaID");

                    b.Property<string>("CNombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("CNombre");

                    b.HasKey("NDiaSemanaID")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CNombre" }, "CNombre")
                        .IsUnique();

                    b.ToTable("TDiaSemana", (string)null);
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TEstadoUsuario", b =>
                {
                    b.Property<int>("NEstadoUsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(12)")
                        .HasColumnName("NEstadoUsuarioID");

                    b.Property<string>("CNombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CNombre");

                    b.HasKey("NEstadoUsuarioID")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CNombre" }, "CNombre")
                        .IsUnique()
                        .HasDatabaseName("CNombre1");

                    b.ToTable("TEstadoUsuario", (string)null);

                    b.HasData(
                        new
                        {
                            NEstadoUsuarioID = 1,
                            CNombre = "Activo"
                        },
                        new
                        {
                            NEstadoUsuarioID = 2,
                            CNombre = "Inactivo"
                        });
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TEstadoVerificacion", b =>
                {
                    b.Property<int>("NEstadoVerificacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(12)")
                        .HasColumnName("NEstadoVerificacion");

                    b.Property<string>("CNombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("CNombre");

                    b.HasKey("NEstadoVerificacionID")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CNombre" }, "CNombre")
                        .IsUnique()
                        .HasDatabaseName("CNombre2");

                    b.ToTable("TEstadoVerificacion", (string)null);

                    b.HasData(
                        new
                        {
                            NEstadoVerificacionID = 1,
                            CNombre = "Verificado"
                        },
                        new
                        {
                            NEstadoVerificacionID = 2,
                            CNombre = "No Verificado"
                        });
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TGrupoSanguineo", b =>
                {
                    b.Property<int>("NGrupoSanguineoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(12)")
                        .HasColumnName("NGrupoSanguineoID");

                    b.Property<string>("CNombre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CNombre");

                    b.HasKey("NGrupoSanguineoID")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CNombre" }, "CNombre")
                        .IsUnique()
                        .HasDatabaseName("CNombre3");

                    b.ToTable("TGrupoSanguineo", (string)null);
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TLogins", b =>
                {
                    b.Property<int>("NLoginID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(32)")
                        .HasColumnName("NLoginID");

                    b.Property<DateTime>("DFechaLogin")
                        .HasColumnType("DateTime")
                        .HasColumnName("DFechaLogin");

                    b.Property<int>("NUsuarioFK")
                        .HasColumnType("int(32)");

                    b.HasKey("NLoginID")
                        .HasName("PRIMARY");

                    b.HasIndex("NUsuarioFK");

                    b.ToTable("TLogins", (string)null);
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TRol", b =>
                {
                    b.Property<int>("NRolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(32)")
                        .HasColumnName("NRolID");

                    b.Property<string>("CNombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CNombre");

                    b.HasKey("NRolID")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CNombre" }, "CNombre")
                        .IsUnique()
                        .HasDatabaseName("CNombre4");

                    b.ToTable("TRol", (string)null);

                    b.HasData(
                        new
                        {
                            NRolID = 1,
                            CNombre = "Administrador"
                        },
                        new
                        {
                            NRolID = 2,
                            CNombre = "Paciente"
                        },
                        new
                        {
                            NRolID = 3,
                            CNombre = "Medico"
                        });
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TTipoIdentificacion", b =>
                {
                    b.Property<int>("NTipoIdentificacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(12)")
                        .HasColumnName("NTipoIdentificacion");

                    b.Property<string>("CNombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("CNombre");

                    b.HasKey("NTipoIdentificacionID")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CNombre" }, "CNombre")
                        .IsUnique()
                        .HasDatabaseName("CNombre5");

                    b.ToTable("TTipoIdentificacion", (string)null);
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TUsuarios", b =>
                {
                    b.Property<int>("NUsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(32)")
                        .HasColumnName("nUsuarioID");

                    b.Property<string>("CApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CApellido");

                    b.Property<string>("CEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CEmail");

                    b.Property<string>("CNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CNombre");

                    b.Property<string>("CPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CPassword");

                    b.Property<DateTime>("DFechaRegistro")
                        .HasColumnType("DateTime")
                        .HasColumnName("DFechaRegistro");

                    b.Property<int>("NEstadoUsuarioFK")
                        .HasColumnType("int(12)")
                        .HasColumnName("NEstadoUsuarioFK");

                    b.Property<int>("NEstadoVerificacionFK")
                        .HasColumnType("int(12)")
                        .HasColumnName("NEstadoVerificacionFK");

                    b.Property<int>("NRolFK")
                        .HasColumnType("int(12)")
                        .HasColumnName("NRolFK");

                    b.HasKey("NUsuarioID")
                        .HasName("PRIMARY");

                    b.HasIndex("NEstadoUsuarioFK");

                    b.HasIndex("NEstadoVerificacionFK");

                    b.HasIndex("NRolFK");

                    b.HasIndex(new[] { "CEmail" }, "CEmail")
                        .IsUnique();

                    b.ToTable("TUsuarios", (string)null);
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TLogins", b =>
                {
                    b.HasOne("Api_Mediconnet.Domain.Entities.TUsuarios", "Usuarios")
                        .WithMany("Logins")
                        .HasForeignKey("NUsuarioFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Logins");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TUsuarios", b =>
                {
                    b.HasOne("Api_Mediconnet.Domain.Entities.TEstadoUsuario", "EstadoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("NEstadoUsuarioFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_EstadoUsuarios");

                    b.HasOne("Api_Mediconnet.Domain.Entities.TEstadoVerificacion", "EstadoVerificacion")
                        .WithMany("Usuarios")
                        .HasForeignKey("NEstadoVerificacionFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_EstadoVerificacion");

                    b.HasOne("Api_Mediconnet.Domain.Entities.TRol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("NRolFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Rol");

                    b.Navigation("EstadoUsuario");

                    b.Navigation("EstadoVerificacion");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TEstadoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TEstadoVerificacion", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TRol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TUsuarios", b =>
                {
                    b.Navigation("Logins");
                });
#pragma warning restore 612, 618
        }
    }
}
