// <auto-generated />
using System;
using Api_Mediconnet.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_Mediconnet.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TDiaSemana", b =>
                {
                    b.Property<int>("NDiaSemanaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(12)")
                        .HasColumnName("NDiaSemanaID");

                    b.Property<string>("CNombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("CNombre");

                    b.HasKey("NDiaSemanaID")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CNombre" }, "CNombre")
                        .IsUnique();

                    b.ToTable("TDiaSemana", (string)null);

                    b.HasData(
                        new
                        {
                            NDiaSemanaID = 1,
                            CNombre = "Lunes"
                        },
                        new
                        {
                            NDiaSemanaID = 2,
                            CNombre = "Martes"
                        },
                        new
                        {
                            NDiaSemanaID = 3,
                            CNombre = "Miércoles"
                        },
                        new
                        {
                            NDiaSemanaID = 4,
                            CNombre = "Jueves"
                        },
                        new
                        {
                            NDiaSemanaID = 5,
                            CNombre = "Viernes"
                        },
                        new
                        {
                            NDiaSemanaID = 6,
                            CNombre = "Sábado"
                        },
                        new
                        {
                            NDiaSemanaID = 7,
                            CNombre = "Domingo"
                        });
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TEstadoUsuario", b =>
                {
                    b.Property<int>("NEstadoUsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(12)")
                        .HasColumnName("NEstadoUsuarioID");

                    b.Property<string>("CNombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CNombre");

                    b.HasKey("NEstadoUsuarioID")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CNombre" }, "CNombre")
                        .IsUnique()
                        .HasDatabaseName("CNombre1");

                    b.ToTable("TEstadoUsuario", (string)null);

                    b.HasData(
                        new
                        {
                            NEstadoUsuarioID = 1,
                            CNombre = "Activo"
                        },
                        new
                        {
                            NEstadoUsuarioID = 2,
                            CNombre = "Inactivo"
                        });
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TEstadoVerificacion", b =>
                {
                    b.Property<int>("NEstadoVerificacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(12)")
                        .HasColumnName("NEstadoVerificacion");

                    b.Property<string>("CNombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("CNombre");

                    b.HasKey("NEstadoVerificacionID")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CNombre" }, "CNombre")
                        .IsUnique()
                        .HasDatabaseName("CNombre2");

                    b.ToTable("TEstadoVerificacion", (string)null);

                    b.HasData(
                        new
                        {
                            NEstadoVerificacionID = 1,
                            CNombre = "Verificado"
                        },
                        new
                        {
                            NEstadoVerificacionID = 2,
                            CNombre = "No Verificado"
                        });
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TGrupoSanguineo", b =>
                {
                    b.Property<int>("NGrupoSanguineoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(12)")
                        .HasColumnName("NGrupoSanguineoID");

                    b.Property<string>("CNombre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CNombre");

                    b.HasKey("NGrupoSanguineoID")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CNombre" }, "CNombre")
                        .IsUnique()
                        .HasDatabaseName("CNombre3");

                    b.ToTable("TGrupoSanguineo", (string)null);

                    b.HasData(
                        new
                        {
                            NGrupoSanguineoID = 1,
                            CNombre = "A+"
                        },
                        new
                        {
                            NGrupoSanguineoID = 2,
                            CNombre = "A-"
                        },
                        new
                        {
                            NGrupoSanguineoID = 3,
                            CNombre = "B+"
                        },
                        new
                        {
                            NGrupoSanguineoID = 4,
                            CNombre = "B-"
                        },
                        new
                        {
                            NGrupoSanguineoID = 5,
                            CNombre = "AB+"
                        },
                        new
                        {
                            NGrupoSanguineoID = 6,
                            CNombre = "AB-"
                        },
                        new
                        {
                            NGrupoSanguineoID = 7,
                            CNombre = "O+"
                        },
                        new
                        {
                            NGrupoSanguineoID = 8,
                            CNombre = "O-"
                        });
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TLogins", b =>
                {
                    b.Property<int>("NLoginID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(32)")
                        .HasColumnName("NLoginID");

                    b.Property<DateTime>("DFechaLogin")
                        .HasColumnType("DateTime")
                        .HasColumnName("DFechaLogin");

                    b.Property<int>("NUsuarioFK")
                        .HasColumnType("int(32)");

                    b.HasKey("NLoginID")
                        .HasName("PRIMARY");

                    b.HasIndex("NUsuarioFK");

                    b.ToTable("TLogins", (string)null);
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TPaciente", b =>
                {
                    b.Property<int>("NPacienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(32)")
                        .HasColumnName("NPacienteID");

                    b.Property<string>("CAlergiasGenerales")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("CAlergiasGenerales");

                    b.Property<int>("NGrupoSanguineoFK")
                        .HasColumnType("int(6)")
                        .HasColumnName("NGrupoSanguineoFK");

                    b.Property<int>("NPersonaFK")
                        .HasColumnType("int(32)")
                        .HasColumnName("NPersonaFK");

                    b.HasKey("NPacienteID")
                        .HasName("PRIMARY");

                    b.HasIndex("NPersonaFK")
                        .IsUnique();

                    b.ToTable("TPaciente", (string)null);
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TPersona", b =>
                {
                    b.Property<int>("NPersonaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(32)")
                        .HasColumnName("NPersonaID");

                    b.Property<string>("CDireccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CDireccion");

                    b.Property<string>("CNroConctacto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("CNroConctacto");

                    b.Property<string>("CNroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CNroIdentificacion");

                    b.Property<DateTime>("DFechaNacimiento")
                        .HasColumnType("DateTime")
                        .HasColumnName("DFechaNacimiento");

                    b.Property<string>("ESexo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("ESexo");

                    b.Property<int>("NTipoIdentificacionFK")
                        .HasColumnType("int(32)")
                        .HasColumnName("NTipoIdentificacionFK");

                    b.Property<int>("NUsuarioFK")
                        .HasColumnType("int(32)")
                        .HasColumnName("NUsuarioFK");

                    b.HasKey("NPersonaID")
                        .HasName("PRIMARY");

                    b.HasIndex("NTipoIdentificacionFK");

                    b.HasIndex("NUsuarioFK")
                        .IsUnique();

                    b.HasIndex(new[] { "CNroIdentificacion" }, "CNroIdentificacion")
                        .IsUnique();

                    b.ToTable("TPersona", (string)null);
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TRol", b =>
                {
                    b.Property<int>("NRolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(32)")
                        .HasColumnName("NRolID");

                    b.Property<string>("CNombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CNombre");

                    b.HasKey("NRolID")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CNombre" }, "CNombre")
                        .IsUnique()
                        .HasDatabaseName("CNombre4");

                    b.ToTable("TRol", (string)null);

                    b.HasData(
                        new
                        {
                            NRolID = 1,
                            CNombre = "Administrador"
                        },
                        new
                        {
                            NRolID = 2,
                            CNombre = "Paciente"
                        },
                        new
                        {
                            NRolID = 3,
                            CNombre = "Medico"
                        });
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TTipoIdentificacion", b =>
                {
                    b.Property<int>("NTipoIdentificacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(12)")
                        .HasColumnName("NTipoIdentificacion");

                    b.Property<string>("CNombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("CNombre");

                    b.HasKey("NTipoIdentificacionID")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CNombre" }, "CNombre")
                        .IsUnique()
                        .HasDatabaseName("CNombre5");

                    b.ToTable("TTipoIdentificacion", (string)null);

                    b.HasData(
                        new
                        {
                            NTipoIdentificacionID = 1,
                            CNombre = "Cédula de ciudadanía"
                        },
                        new
                        {
                            NTipoIdentificacionID = 2,
                            CNombre = "Tarjeta de identidad"
                        },
                        new
                        {
                            NTipoIdentificacionID = 3,
                            CNombre = "Registro civil de nacimiento"
                        },
                        new
                        {
                            NTipoIdentificacionID = 4,
                            CNombre = "Cédula de extranjería"
                        },
                        new
                        {
                            NTipoIdentificacionID = 5,
                            CNombre = "Pasaporte"
                        });
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TUsuarios", b =>
                {
                    b.Property<int>("NUsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(32)")
                        .HasColumnName("nUsuarioID");

                    b.Property<string>("CApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CApellido");

                    b.Property<string>("CEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CEmail");

                    b.Property<string>("CNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CNombre");

                    b.Property<string>("CPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CPassword");

                    b.Property<DateTime>("DFechaRegistro")
                        .HasColumnType("DateTime")
                        .HasColumnName("DFechaRegistro");

                    b.Property<int>("NEstadoUsuarioFK")
                        .HasColumnType("int(12)")
                        .HasColumnName("NEstadoUsuarioFK");

                    b.Property<int>("NEstadoVerificacionFK")
                        .HasColumnType("int(12)")
                        .HasColumnName("NEstadoVerificacionFK");

                    b.Property<int>("NRolFK")
                        .HasColumnType("int(12)")
                        .HasColumnName("NRolFK");

                    b.HasKey("NUsuarioID")
                        .HasName("PRIMARY");

                    b.HasIndex("NEstadoUsuarioFK");

                    b.HasIndex("NEstadoVerificacionFK");

                    b.HasIndex("NRolFK");

                    b.HasIndex(new[] { "CEmail" }, "CEmail")
                        .IsUnique();

                    b.ToTable("TUsuarios", (string)null);
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TLogins", b =>
                {
                    b.HasOne("Api_Mediconnet.Domain.Entities.TUsuarios", "Usuarios")
                        .WithMany("Logins")
                        .HasForeignKey("NUsuarioFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Logins");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TPaciente", b =>
                {
                    b.HasOne("Api_Mediconnet.Domain.Entities.TPersona", "Personas")
                        .WithOne("Paciente")
                        .HasForeignKey("Api_Mediconnet.Domain.Entities.TPaciente", "NPersonaFK");

                    b.Navigation("Personas");
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TPersona", b =>
                {
                    b.HasOne("Api_Mediconnet.Domain.Entities.TTipoIdentificacion", "TipoIdentificacion")
                        .WithMany("Personas")
                        .HasForeignKey("NTipoIdentificacionFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Personas_TipoIdentificacion");

                    b.HasOne("Api_Mediconnet.Domain.Entities.TUsuarios", "Usuarios")
                        .WithOne("Personas")
                        .HasForeignKey("Api_Mediconnet.Domain.Entities.TPersona", "NUsuarioFK");

                    b.Navigation("TipoIdentificacion");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TUsuarios", b =>
                {
                    b.HasOne("Api_Mediconnet.Domain.Entities.TEstadoUsuario", "EstadoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("NEstadoUsuarioFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_EstadoUsuarios");

                    b.HasOne("Api_Mediconnet.Domain.Entities.TEstadoVerificacion", "EstadoVerificacion")
                        .WithMany("Usuarios")
                        .HasForeignKey("NEstadoVerificacionFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_EstadoVerificacion");

                    b.HasOne("Api_Mediconnet.Domain.Entities.TRol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("NRolFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Rol");

                    b.Navigation("EstadoUsuario");

                    b.Navigation("EstadoVerificacion");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TEstadoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TEstadoVerificacion", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TPersona", b =>
                {
                    b.Navigation("Paciente")
                        .IsRequired();
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TRol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TTipoIdentificacion", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TUsuarios", b =>
                {
                    b.Navigation("Logins");

                    b.Navigation("Personas")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
