// <auto-generated />
using Api_Mediconnet.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_Mediconnet.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250619194941_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TRol", b =>
                {
                    b.Property<int>("NRolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(12)")
                        .HasColumnName("NRolID");

                    b.Property<string>("CNombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CNombre");

                    b.HasKey("NRolID")
                        .HasName("PRIMARY");

                    b.ToTable("TRol", (string)null);
                });

            modelBuilder.Entity("Api_Mediconnet.Domain.Entities.TUsuarios", b =>
                {
                    b.Property<int>("NUsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(32)")
                        .HasColumnName("nUsuarioID");

                    b.Property<string>("CApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CApellido");

                    b.Property<string>("CEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CEmail");

                    b.Property<string>("CNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CNombre");

                    b.Property<string>("CPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CPassword");

                    b.HasKey("NUsuarioID")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CEmail" }, "CEmail")
                        .IsUnique();

                    b.ToTable("tUsuarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
